'use client';
import {FormEvent,useState} from 'react';
import Link from 'next/link';

export default function RegisterRider(){
 const[done,setDone]=useState(false);
 function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=new FormData(e.currentTarget);const profile=Object.fromEntries(form.entries());localStorage.setItem('pwc-rider-profile',JSON.stringify(profile));setDone(true)}
 if(done)return <main><header className="topbar"><div><span className="mark">PWC</span><strong> RIDER</strong></div></header><section className="hero"><p className="eyebrow">REGISTRATION COMPLETE</p><h1>You're race-day ready</h1><p>Your rider profile has been saved on this device.</p></section><section className="panel alert"><h2>Next: enter an event</h2><p className="notificationHelp">We’ll connect this profile to event entry, classes and targeted Race Control alerts next.</p><Link className="actionCard" href="/rider"><strong>Go to Rider Mode →</strong></Link></section></main>;
 return <main><header className="topbar"><div><span className="mark">PWC</span><strong> RIDER REGISTRATION</strong></div><Link href="/rider">Back</Link></header><section className="hero"><p className="eyebrow">RIDER PROFILE</p><h1>Register to race</h1><p>Create your rider profile once, then use it for future event entries.</p></section><form className="panel" onSubmit={submit}><p className="eyebrow">PERSONAL DETAILS</p><h2>About you</h2><div className="formGrid"><label>First name<input name="firstName" required placeholder="First name"/></label><label>Last name<input name="lastName" required placeholder="Last name"/></label><label>Email<input name="email" type="email" required placeholder="you@example.com"/></label><label>Mobile<input name="mobile" type="tel" required placeholder="Mobile number"/></label><label>Country<input name="country" required defaultValue="New Zealand"/></label><label>Club / association<input name="club" placeholder="Optional"/></label></div><p className="eyebrow" style={{marginTop:32}}>RACE DETAILS</p><h2>Your race identity</h2><div className="formGrid"><label>Race number<input name="raceNumber" required placeholder="e.g. 123"/></label><label>Licence number<input name="licenceNumber" placeholder="If applicable"/></label><label>Ski make<input name="skiMake" placeholder="e.g. Yamaha"/></label><label>Ski model<input name="skiModel" placeholder="e.g. GP SVHO"/></label></div><p className="eyebrow" style={{marginTop:32}}>EMERGENCY CONTACT</p><div className="formGrid"><label>Contact name<input name="emergencyName" required/></label><label>Contact mobile<input name="emergencyMobile" type="tel" required/></label></div><button type="submit" style={{marginTop:32}}>Create rider profile</button></form><footer>PWC Race Control • Rider Registration</footer></main>;
}