'use client';
import {useState} from 'react';
import Link from 'next/link';

type Entry={id:number;first_name:string;last_name:string;race_number:string;club?:string;classes:string[];checked_in:boolean;scrutineering_status:'pending'|'passed'|'failed';payment_status:'unpaid'|'paid'|'waived';status:string};
export default function RaceDay(){const[key,setKey]=useState('');const[entries,setEntries]=useState<Entry[]>([]);const[msg,setMsg]=useState('Enter the Race Control key to load event entries.');const[busy,setBusy]=useState(false);
async function load(){setBusy(true);try{const r=await fetch('/api/entries/race-day',{headers:{'x-race-control-key':key}});const d=await r.json();if(!r.ok)throw Error(d.error);setEntries(d.entries);setMsg(`${d.entries.length} event ${d.entries.length===1?'entry':'entries'} loaded.`)}catch(e:any){setMsg(e.message)}finally{setBusy(false)}}
async function update(e:Entry,patch:Partial<Entry>){const next={...e,...patch};setEntries(x=>x.map(v=>v.id===e.id?next:v));try{const r=await fetch('/api/entries/race-day',{method:'PATCH',headers:{'Content-Type':'application/json','x-race-control-key':key},body:JSON.stringify({id:e.id,checked_in:next.checked_in,scrutineering_status:next.scrutineering_status,payment_status:next.payment_status})});const d=await r.json();if(!r.ok)throw Error(d.error);setEntries(x=>x.map(v=>v.id===e.id?d.entry:v))}catch(err:any){setMsg(err.message);setEntries(x=>x.map(v=>v.id===e.id?e:v))}}
const cleared=entries.filter(e=>e.status==='cleared').length;
return <main><header className="topbar"><Link className="back" href="/">‹ Race Control</Link><span className="live">● RACE DAY</span></header><section className="hero"><p className="eyebrow">WELLINGTON CHAMPIONSHIP</p><h1>Race Day Check-in</h1><p>Entry • payment • scrutineering • clearance</p></section><section className="grid stats"><article><span>Entries</span><strong>{entries.length}</strong></article><article><span>Checked in</span><strong>{entries.filter(e=>e.checked_in).length}</strong></article><article><span>Cleared</span><strong>{cleared}</strong></article></section><section className="panel"><p className="eyebrow">RACE CONTROL ACCESS</p><div style={{display:'flex',gap:12,flexWrap:'wrap'}}><input style={{flex:1}} type="password" placeholder="Race Control security key" value={key} onChange={e=>setKey(e.target.value)}/><button onClick={load} disabled={busy||!key}>{busy?'Loading…':'Load event entries'}</button></div><small className="notificationHelp">{msg}</small></section><section className="panel"><div className="sectionTitle"><div><p className="eyebrow">EVENT ENTRIES</p><h2>Rider clearance</h2></div></div><div className="resultsList">{entries.map(e=><div key={e.id} style={{gridTemplateColumns:'80px 1.4fr 1fr 1fr 1fr'}}><strong>#{e.race_number}</strong><span><b>{e.first_name} {e.last_name}</b><br/><small>{e.classes?.join(' • ')}</small></span><label><input type="checkbox" checked={e.checked_in} onChange={x=>update(e,{checked_in:x.target.checked})}/> Check-in</label><select value={e.scrutineering_status} onChange={x=>update(e,{scrutineering_status:x.target.value as Entry['scrutineering_status']})}><option value="pending">Scrutineering: pending</option><option value="passed">✓ Scrutineering passed</option><option value="failed">✕ Scrutineering failed</option></select><select value={e.payment_status} onChange={x=>update(e,{payment_status:x.target.value as Entry['payment_status']})}><option value="unpaid">Payment: unpaid</option><option value="paid">✓ Paid</option><option value="waived">Payment waived</option></select><span className={`status ${e.status==='cleared'?'finished':'dns'}`}>{e.status==='cleared'?'✓ CLEARED TO RACE':'NOT CLEARED'}</span></div>)}</div>{!entries.length&&<p className="notificationHelp">No entries loaded yet.</p>}</section><footer>Race Control • Race-day administration</footer></main>}
